<!-- Individual post page, routed from landing page post click -->
<template>
  <Layout :title="$page.project.title">
    <article class="project-post">
      <!-- our imported header at the top - title etc -->
      <project-header
        :title="$page.project.title"
        :categories="$page.project.categories"
        :year="$page.project.year"
        :author="$page.project.author"
      />
      <!-- post header image -->
      <g-image
        class="thumnail"
        :src="$page.project.thumbnail"
        :alt="$page.project.title"
      />
      <!-- parsed post flat-file content -->
      <div class="content" v-html="$page.project.content" />
    </article>
  </Layout>
</template>

<!--
Query the metadata for an individual project
./projects
-->
<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    year
    categories
    content
    author
  }
}
</page-query>

<script>
import ProjectHeader from "@/components/ProjectHeader";

export default {
  components: {
    ProjectHeader,
  },
  mounted() {
    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      (element) =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  },
};
</script>

<style lang="scss">
.project-post {
  padding: 0 2rem;
  margin-bottom: 8rem;
}
img {
  width: 100% !important;
  margin-bottom: 2rem;
}
p {
  margin: 0;
}
.content-text {
  padding: 2rem 0 2rem 0;
  font-size: 2rem;
  font-weight: 400;
  margin-left: 0;
  max-width: 780px;
  line-height: 1.5;
  @media (min-width: 920px) {
    margin-left: 40%;
  }
}
</style>