---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: photographyposts
  label: PhotographyPosts
  create: documents
  match: "**/*"
  templates:
  - photographypost
- type: directory
  path: projects
  label: Projects
  create: all
  match: "**/*"
- type: document
  path: src/data/theme.json
  label: Theme options
upload_dir: ''
public_path: https://brightbluewaves.s3.us-east-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
