---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: author
  type: text
  config:
    required: false
  label: author
  description: 'Author of the post. '
pages:
- projects/birds-sun.md
- projects/january-wednesday-morning-sdwim.md
